### ISSUE TITLE
Sometimes The home route just gives empty data.

### ISSUE THREAD

**Issue by JayadityaGit** [ghoshRitesh12/aniwatch-api#19]
### Describe the bug

it is not able to fetch the data like trending etc , instead it just gives an empty array in the home route (This happening frequently, it is dissaperaing in the next reload).

### Expected behavior

![notbug](https://github.com/ghoshRitesh12/aniwatch-api/assets/96861162/1d5c7acd-115f-4ed5-8339-14149b2e16e5)

### Actual behavior

![bug](https://github.com/ghoshRitesh12/aniwatch-api/assets/96861162/4768ba6e-5d78-4145-9d88-9f2684d87cab)

### Additional context

The bug not appearing all the time, but it is becoming frequent....

**Comment by ghoshRitesh12** [comment]
I will have this bug on hold for a while. If the array is empty a times then there maybe some other problem. If this becomes even more frequent then I'll try to resolve it. What do you say @JayadityaGit?

**Comment by JayadityaGit** [comment]
First of all thanks man for creating this api, my main motivation is to build an anime website, for that I learned web development (MERN) ,so coming to the question i really want to understand this web scraping can you suggest a resource so I can build my anime web scrapper.  I know it is using cheerio and axios , but I feel overwhelmed looking at this codebase. Can you help me like giving a roadmap or something. I just want to have control over my scrapper for future issues.

Happy New year 🎊

**Comment by ghoshRitesh12** [comment]
Happy New Year 🎊✨

Basically the code base feels overwhelming because it follows some principles of clean code, hence it's so kuch modularized. It's really easy to figure out, for every endpoint you send a req to aniwatch's endpoint grabbing the html and extracting the data via cheerio and sending back the json response. Basically that's how most endpoints work in this api.

Here's a [resource](https://youtu.be/dXjKh66BR2U?si=_oVcV_D6HNH0Dano) that may help you understand web scraping

**Comment by ghoshRitesh12** [comment]
@JayadityaGit I am closing this issue as not planned. If this issue worsens then do open another issue.

**Comment by JayadityaGit** [comment]
No problem, since the release of movie-web.app , I was awe struck by the possibilities, what a streaming platform can do... 

Thx for guidance and the resource.

**Comment by ghoshRitesh12** [comment]
@JayadityaGit anytime.
