### ISSUE TITLE
Suggestion: isDub Boolean when fetching Episodes List

### ISSUE THREAD

**Issue by ErickLimaS** [ghoshRitesh12/aniwatch-api#48]
Hi, first a would like to say that this API is amazing!

Now, the suggestion is that, it would be good to have the information of which of the episodes on the episodes list fetched is dubbed.

Like, in the fetch episodes route: **/anime/episodes/konosuba-gods-blessing-on-this-wonderful-world-342**

It returns only **episodeId, isFiller, number, title**. A **isDub** with true || false would be good i guess.

**Comment by WBRK-dev** [comment]
It is impossible to check each episode if it is a dubbed episode.
That's why you can use `/anime/servers?episodeId=konosuba-gods-blessing-on-this-wonderful-world-342?ep=7736`. 
The response will give you three arrays: `sub`, `dub` and `raw`. 
You will know if the episode has dubbed version if the `dub` array has at least one item in it.

You can get the dubbed source from `/anime/episode-srcs?id=konosuba-gods-blessing-on-this-wonderful-world-342?ep=7736&category=dub`.
Make sure you specify `category=dub` in the url search params.
Thats how the api knows you want the dubbed version of the episode.

**Comment by ErickLimaS** [comment]
>You can get the dubbed source from /anime/episode-srcs?id=konosuba-gods-blessing-on-this-wonderful-world-342?ep=7736&category=dub

Yeah, i knew this endpoint already. But i got a workaround already, where i just fetch the episodes list which, besides the episodes, returns the amount of dubbed episodes, then i just slice them according to this number to get only the Dubbed ones.

So thats it, thanks for the reply

**Comment by WBRK-dev** [comment]
Good solution.
Have fun using the api. 😁
