### ISSUE TITLE
Japanese Title is not available for all the animes

### ISSUE THREAD

**Issue by uploadkeeper** [ghoshRitesh12/aniwatch-api#52]
I was going through this then what I got is that Japanese Title is not available for all anime it is only showing in Related anime and Most popular, hopping that you would add Japanese Title for all anime like Related anime

**Comment by WBRK-dev** [comment]
To achieve this you would need to create another microservice that merges subtitles in every episode that is available.
This could be done as a background service that slowly goes over every episode that is available on hianime or this could be done when the episode source is requested by the client.

Although it may sound convenient this is actually really bad for both your server and the client.
For example if you are going to alter the episode sources you would need to store the episode locally on your own server.
This will be going to cost you some gigabytes of storage the longer you host this service.
Subtitles embedded in the video source is also bad for the clients accessibility because if the client wants bigger font size you would need to create another video with bigger font size.

That's why you want to just use the episode source given with the request and create your own subtitle overlay on top of the video.

**Comment by WBRK-dev** [comment]
Oops I just saw that I posted this response on the wrong issue. 
:/

**Comment by WBRK-dev** [comment]
@uploadkeeper I fixed this issue in #60
